### ISSUE TITLE
生徒作成画面で既に存在するnameを指定すると上書きされる

### ISSUE THREAD

**Issue by doi-wingarc** [suzuki-hirokazu-wingarc/bridgedu#13]
上書きされます
- Serviceで怒る
- 許容する

**Comment by suzuki-hirokazu-wingarc** [comment]
チャッピーに聞いたらServiceで怒って例外をスローするべきらしいのでそうします。
Controllerで例外をキャッチして、生徒作成画面に戻すようにします。
`BindingResult::rejectValue`で"username"に"already exist"みたいなことを乗せられるみたいなので、
`<span th:if="${#fields.hasErrors('username')}" th:errors="*{username}"></span>`でエラーメッセージを表示できるはずです。たぶんメイビー

**Comment by suzuki-hirokazu-wingarc** [comment]
なおしました
