### ISSUE TITLE
milestone/taskに非表示にする機能を付けるべきかも

### ISSUE THREAD

**Issue by doi-wingarc** [suzuki-hirokazu-wingarc/bridgedu#22]
- milestone/taskのdeleteは健全じゃない気がしていて、deleteする操作だけど実際には非表示になっているだけってしたくないですか
- 教師からは非表示の項目も(もちろん明確に非表示項目とわかるようにした上で)見れるようにした方が健全

**Comment by suzuki-hirokazu-wingarc** [comment]
tasksテーブルにenabled属性を追加して、Studentはfalseなら表示しないとかできそうですね

**Comment by doi-wingarc** [comment]
そんなかんじ

**Comment by suzuki-hirokazu-wingarc** [comment]
タスク削除でだいたい達成してるので閉じます
