### ISSUE TITLE
不可逆なのでマジで削除します？的なアラートほしくなりました

### ISSUE THREAD

**Issue by suzuki-hirokazu-wingarc** [suzuki-hirokazu-wingarc/bridgedu#84]
不可逆なのでマジで削除します？的なアラートほしくなりました

_Originally posted by @doi-wingarc in https://github.com/suzuki-hirokazu-wingarc/bridgedu/issues/82#issuecomment-1612294621_

**Comment by suzuki-hirokazu-wingarc** [comment]
フロントのJSでやるのがよさげ

**Comment by doi-wingarc** [comment]
する
