### ISSUE TITLE
削除ボタンのUIを検討する必要がありそうです

### ISSUE THREAD

**Issue by suzuki-hirokazu-wingarc** [suzuki-hirokazu-wingarc/bridgedu#85]
そもそも削除ボタンが編集の中にあったほうがうれしそうです

_Originally posted by @doi-wingarc in https://github.com/suzuki-hirokazu-wingarc/bridgedu/issues/82#issuecomment-1612296087_

**Comment by doi-wingarc** [comment]
やる
